educaction_proj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve

# from content.views import dashboard
from home.views import *
from django.views import static
from django.conf import settings
from general import set_lang as core_views
# from home import views as home_views
# from django.conf.urls import handler404, handler500

# from general import set_lang as core_views


urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media'),
]
# handler404 = home_views.error_404
# translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
# urlpatterns += [

    url(r'^set-language/$', core_views.set_language, name='set_language'),
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^', include("home.urls", namespace="home")),
    url(r'^panel/', include("panel.urls", namespace="panel")),
    url(r'^', include("content.urls", namespace="content")),

    url(r'^auth/', include("base_user.urls", namespace="base-user")),
)
# ]

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^about/$', about, name='about'),
	# url(r'^error_404/$', error_404, name='error_404'),
	url(r'^programs/$', search, name='search'),
	url(r'^programs/deatil-(?P<id>\d+)/(?P<slug>[\w-]+)/$', program_detail, name='program-detail'),
	url(r'^contact/$', contact, name='contact-us'),
	url(r'^online-exam/$', online_exam, name='online-exam'),
	url(r'^online-exam/detail/(?P<id>[\w-]+)/$', online_exam_detail, name='online-exam-detail'),
	url(r'^online-exam/detail/(?P<id>[\w-]+)/check/$', online_exam_detail_check, name='online-exam-detail-check'),
	url(r'^page/(?P<slug>[\w-]+)/$', static_page, name='static-page'),

]

panel/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _

from base_user.tools.common import USERTYPES
from content.forms import PhoneNumberField
from content.models import ExamUser
from panel.models import *

GUser = get_user_model()


ORDERTYPECHOICE  = (
    ('-', _('Desc')),
    ('',_('Asc')),
)

class AppealSearchForm(forms.Form):
    first_name = forms.CharField(max_length=255,label=_('First name'), required=False, widget=forms.TextInput(attrs={'placeholder': _('First name'), 'autocomplete': 'off','class': 'form-control', }))
    last_name = forms.CharField(max_length=255,label=_('Last name'), required=False, widget=forms.TextInput(attrs={'placeholder': _('Last name'), 'autocomplete': 'off','class': 'form-control', }))
    phone = forms.CharField(max_length=255,label=_('Phone'), required=False, widget=forms.TextInput(attrs={'placeholder': _('Phone'), 'autocomplete': 'off','class': 'form-control', }))
    country = forms.ChoiceField(label=_('Country'), required=False, choices=[], widget=forms.Select(attrs={'placeholder': _('Country'), 'autocomplete': 'off','class': 'form-control', }))
    language = forms.ChoiceField(label=_('Language'), required=False, choices=[], widget=forms.Select(attrs={'placeholder': _('Language'), 'autocomplete': 'off','class': 'form-control', }))
    profession = forms.ChoiceField(label=_('Profession'), required=False, choices=[], widget=forms.Select(attrs={'placeholder': _('Profession'), 'autocomplete': 'off','class': 'form-control', }))
    profession_section = forms.ChoiceField(label=_('Profession section'), required=False, choices=[], widget=forms.Select(attrs={'placeholder': _('Profession section'), 'autocomplete': 'off','class': 'form-control', }))
    search = forms.CharField(max_length=255,label=_('Search'), required=False, widget=forms.TextInput(attrs={'placeholder': _('Search'), 'autocomplete': 'off','class': 'form-control', }))
    field_list = forms.ChoiceField(choices=[],label=_('Field'),  required=True, widget=forms.Select(attrs={'placeholder': _('Field'), 'autocomplete': 'off','class': 'form-control', }))
    order_type = forms.ChoiceField(choices=ORDERTYPECHOICE ,label=_('Order'),  required=False, widget=forms.Select(attrs={'placeholder': _('Order'), 'autocomplete': 'off','class': 'form-control', }))
    def __init__(self, field_list_choice, *args, **kwargs):
        super(AppealSearchForm, self).__init__(*args, **kwargs)

        self.fields['field_list'].choices = field_list_choice

class AppealCourseSearchForm(forms.Form):
    first_name = forms.CharField(max_length=255,label=_('First name'), required=False, widget=forms.TextInput(attrs={'placeholder': _('First name'), 'autocomplete': 'off','class': 'form-control', }))
    last_name = forms.CharField(max_length=255,label=_('Last name'), required=False, widget=forms.TextInput(attrs={'placeholder': _('Last name'), 'autocomplete': 'off','class': 'form-control', }))
    phone = forms.CharField(max_length=255,label=_('Phone'), required=False, widget=forms.TextInput(attrs={'placeholder': _('Phone'), 'autocomplete': 'off','class': 'form-control', }))
    course = forms.ChoiceField(label=_('Language Course'), required=False, choices=[], widget=forms.Select(attrs={'placeholder': _('Language Course'), 'autocomplete': 'off','class': 'form-control', }))
    search = forms.CharField(max_length=255,label=_('Search'), required=False, widget=forms.TextInput(attrs={'placeholder': _('Search'), 'autocomplete': 'off','class': 'form-control', }))
    field_list = forms.ChoiceField(choices=[],label=_('Field'),  required=True, widget=forms.Select(attrs={'placeholder': _('Field'), 'autocomplete': 'off','class': 'form-control', }))
    order_type = forms.ChoiceField(choices=ORDERTYPECHOICE ,label=_('Order'),  required=False, widget=forms.Select(attrs={'placeholder': _('Order'), 'autocomplete': 'off','class': 'form-control', }))
    def __init__(self, field_list_choice, *args, **kwargs):
        super(AppealCourseSearchForm, self).__init__(*args, **kwargs)

        self.fields['field_list'].choices = field_list_choice



class GeneralSearchForm(forms.Form):
    search = forms.CharField(max_length=255,label=_('Search'), required=False, widget=forms.TextInput(
        attrs={'placeholder': _('Search'), 'autocomplete': 'off',
               'class': 'form-control', }))
    field_list = forms.ChoiceField(choices=[],label=_('Field'),  required=True, widget=forms.Select(attrs={'placeholder': _('Field'), 'autocomplete': 'off','class': 'form-control', }))
    order_type = forms.ChoiceField(choices=ORDERTYPECHOICE ,label=_('Order'),  required=False, widget=forms.Select(attrs={'placeholder': _('Order'), 'autocomplete': 'off','class': 'form-control', }))
    def __init__(self, field_list_choice, *args, **kwargs):
        super(GeneralSearchForm, self).__init__(*args, **kwargs)

        self.fields['field_list'].choices = field_list_choice




class EmployeeForm(forms.Form):
    name = forms.CharField(required=True,max_length=254, label="Name", error_messages={})
    surname = forms.CharField(required=True,max_length=254, label="Surname", error_messages={})
    email = forms.EmailField(required=True,error_messages={},label=_('Email'))
    usertype = forms.ChoiceField(choices=USERTYPES,required=True,error_messages={},label=_('Type'), widget=forms.Select(attrs={'placeholder': _("Type"),'class':'form-control'}))
    phone = PhoneNumberField(max_length=50,label=_('Phone'),  required=True, widget=forms.TextInput(attrs={'placeholder': _('Phone'), 'Language': 'off','class': 'form-control has-icon', 'style':'width:100%'}))
    password = forms.CharField(required=True, min_length=6,label=_("Password"))
    retype_password = forms.CharField(required=True,min_length=6,label=_("Password type"))


    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget = forms.TextInput(attrs={
            'placeholder': _("Ad"),'class':'form-control'})
        self.fields['surname'].widget = forms.TextInput(attrs={
            'placeholder': _("Soyad"),'class':'form-control'})
        self.fields['email'].widget = forms.EmailInput(attrs={
            'placeholder': _("Email"),'class':'form-control'})
        self.fields['phone'].widget = forms.TextInput(attrs={
            'placeholder': _("Nömrə"),'class':'form-control'})
        self.fields['password'].widget = forms.PasswordInput(attrs={
            'placeholder': _("Şifrə"),'class':'form-control'})
        self.fields['retype_password'].widget = forms.PasswordInput(attrs={
            'placeholder': _("Şifrə"),'class':'form-control'})

    def clean(self):
        cleaned_data = super(EmployeeForm, self).clean()

        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('retype_password')
        user_email_obj = GUser.objects.filter(email=email)
        if user_email_obj:
            self._errors['email'] = _('Email is allready use')
        if user_email_obj:
            self._errors['username'] = _('Email is allready use')
        if password and password_confirm:
            if password != password_confirm:
                raise forms.ValidationError(_("Passwords not same"))
        return cleaned_data





class EmployeeEditForm(forms.Form):
    name = forms.CharField(required=True,max_length=254, label="Ad", error_messages={})
    surname = forms.CharField(required=True,max_length=254, label="Soyad", error_messages={})
    email = forms.EmailField(required=True,error_messages={},label=_('Email'))
    usertype = forms.ChoiceField(choices=USERTYPES,required=True,error_messages={},label=_('Type'), widget=forms.Select(attrs={'placeholder': _("Type"),'class':'form-control'}))
    phone = forms.CharField(required=True,error_messages={},label=_('Nömrə'))
    password = forms.CharField(required=False,label=_("Şifrə"))
    retype_password = forms.CharField(required=False,label=_("Şifrə təsdiqi"))

    user_id = 0

    def __init__(self,user_id, *args, **kwargs):
        super(EmployeeEditForm, self).__init__(*args, **kwargs)
        self.user_id = user_id
        self.fields['name'].widget = forms.TextInput(attrs={'placeholder': _("Ad"),'class':'form-control'})
        self.fields['surname'].widget = forms.TextInput(attrs={'placeholder': _("Soyad"),'class':'form-control'})
        self.fields['email'].widget = forms.EmailInput(attrs={'placeholder': _("Email"),'class':'form-control'})
        self.fields['phone'].widget = forms.TextInput(attrs={'placeholder': _("Nömrə"),'class':'form-control'})
        self.fields['password'].widget = forms.PasswordInput(attrs={'placeholder': _("Şifrə"),'class':'form-control'})
        self.fields['retype_password'].widget = forms.PasswordInput(attrs={'placeholder': _("Şifrə təsdiqi"),'class':'form-control'})


    def clean(self):
        cleaned_data = super(EmployeeEditForm, self).clean()

        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('retype_password')

        user_email_obj = GUser.objects.filter(email=email).exclude(id=self.user_id)
        if user_email_obj:
            self._errors['email'] = _('Email is allready use')
        if user_email_obj:
            self._errors['username'] = _('Email is allready use')
        if password:
            if password and password_confirm:
                if password != password_confirm:
                    raise forms.ValidationError(_("Passwords not same"))
        return cleaned_data


class AppealProgramModelForm(forms.ModelForm):

    class Meta:
        model = AppealProgram
        fields = ('first_name',
                  'last_name',
                  'email',
                  'note',
                  'phone',
                  'program',
                  )
        widgets = {

templates/pages/language-course-datail.html
{% extends 'main-base.html' %}
{% load static %}{% load i18n %}
{% block title_block %}
{% trans 'Language courses' %} - {{ data_item.title }}
{% endblock %}
{% block css_block %}

{% endblock %}
{% block content_block %}

    <div class="rt-breadcump rt-breadcump-height">
        <div class="rt-page-bg rtbgprefix-cover" style="background-image: url({% static 'local/assets/images/backgrounds/bredcump.png' %})">
        </div><!-- /.rt-page-bg -->
        <div class="container">
            <div class="row rt-breadcump-height">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h3>{{ data_item.title }}</h3>
                        <div class="breadcrumbs">
                            <span class="divider"><i class="icofont-home"></i></span>
                            <a href="{% url 'home:index' %}" title="Home">{% trans 'Home' %}</a>
                            <span class="divider"><i class="icofont-simple-right"></i></span>
                            {{ data_item.title }}

                        </div><!-- /.breadcrumbs -->
                    </div><!-- /.breadcrumbs-content -->
                </div><!-- /.col-12 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.rt-bredcump -->


    <section class="content-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="hotel-tabs">
                        <div class="flight-list-box rt-mb-40">
                            <ul class="nav rt-tab-nav-1 pill  pl-md-4 pr-md-4" id="myTab-2"
                                role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="rt-itm_1-tab" data-toggle="tab" href="#rt-itm_1"
                                        role="tab" aria-controls="rt-itm_1" aria-selected="true">{% trans 'Description' %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="rt-itm_2-tab" data-toggle="tab" href="#rt-itm_2" role="tab"
                                        aria-controls="rt-itm_2" aria-selected="false">{% trans 'Apply the course' %}</a>
                                </li>
                            </ul>
                        </div><!-- /.hotle-del-box -->

                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="rt-itm_1" role="tabpanel"
                                aria-labelledby="rt-itm_1-tab">
                                <div class="flight-list-box rt-mb-30">
                                    <div class="inner-content rt-pl-15">
                                        <h4 class="badge-hilighit color--1 f-size-14 text-white text-font text-uppercase rt-mb-30 rt-mt-15 rt-strong">
                                            {{ data_item.title }}
                                        </h4>
                                        {% autoescape off %}
                                            {{ data_item.content }}
                                        {% endautoescape %}

                                    </div><!-- /.inner-content -->
                                </div><!-- /.flight-list-box -->
                            </div>
                            <div class="tab-pane fade" id="rt-itm_2" role="tabpanel" aria-labelledby="rt-itm_2-tab">
                                <div class="flight-list-box rt-mb-30 pt-30">
                                    <h4 class="f-size-24 text-capitalize rt-mb-30  rt-semiblod">{% trans 'Apply the course' %}</h4>
                                    <form action="" method="post" class="rt-form rt-line-form flight-lable" id="main-post-form-data">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 rt-mb-30 ">
                                                <label for="fst-name">{% trans 'First name' %}</label>
                                                {{ form.first_name }}
                                            </div><!-- /.col-md-6 -->
                                            <div class="col-md-6 rt-mb-30">
                                                <label for="lst-name">{% trans 'Last name' %}</label>
                                                {{ form.last_name }}
                                            </div><!-- /.col-md-6 -->
                                            <div class="col-md-6 rt-mb-30 ">
                                                <label for="fst-name">{% trans 'Email' %}</label>
                                                {{ form.email }}
                                            </div><!-- /.col-md-6 -->
                                            <div class="col-md-6 rt-mb-30">
                                                <label for="lst-name">{% trans 'Phone' %}</label>
                                                {{ form.phone }}
                                            </div><!-- /.col-md-6 -->
                                            <div class="col-lg-6 rt-mb-30">
                                            </div><!-- /.col-md-6 -->
                                            <div class="col-md-6">
                                                <button type="submit" class="rt-btn rt-gradient3 pill text-uppercase ">{% trans 'Apply' %}</button>
                                            </div>
                                        </div><!-- /.row -->
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div><!-- /.hotel-tabs -->
                </div><!-- /.col-12 -->
            </div><!-- /.row -->


        </div><!-- /.container -->
    </section>

{% endblock %}
{% block js_block %}
<script type='text/javascript' src="https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/dist/jquery.inputmask.bundle.js"></script>
    <script>
        $("#id_phone").inputmask({"mask": "(999) 999-9999"});
    </script>
    <script>
    $(".se-pre-con").hide();
    var form_submit = false;
        $( "#main-post-form-data" ).submit(function( event ) {
          event.preventDefault();
          if (!form_submit){
              form_submit = true;
                {#$(".se-pre-con").show();#}
                $.ajax({
                    url: '',
                    type: 'post',
                      data: new FormData(this), // Data sent to server, a set of key/value pairs (i.e. form fields and values)
                      contentType: false, // The content type used when sending data to the server.
                      cache: false, // To unable request pages to be cached
                      processData: false,
                        error: function (request, status, error) {
                            form_submit = false;
                            Swal.fire({
                                type: 'error',
                                title: '{% trans 'Xəta baş verdi' %}',
                                html: err.toString(),
                            });
                        },
                    success: function(data){
                        form_submit = false;
                        document.getElementById("main-post-form-data").reset();
                      if (data['code']){
                            Swal.fire({
                                type: 'success',
                                title: data['text'],
                            });
                      }else{
                        form_submit = false;
                        Swal.fire({
                            type: 'error',
                            html: data['text'],
                        });
                      }
                    }
                })
          }else{
            {#$(".se-pre-con").hide();#}
            Swal.fire({
                type: 'info',
                title: '{% trans 'Gözləyin' %}',
                {#html: err.toString(),#}
            });
          }
        });
    </script>
{% endblock %}