educaction_proj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve

# from content.views import dashboard
from home.views import *
from django.views import static
from django.conf import settings
from general import set_lang as core_views
# from home import views as home_views
# from django.conf.urls import handler404, handler500

# from general import set_lang as core_views


urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media'),
]
# handler404 = home_views.error_404
# translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
# urlpatterns += [

    url(r'^set-language/$', core_views.set_language, name='set_language'),
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^', include("home.urls", namespace="home")),
    url(r'^panel/', include("panel.urls", namespace="panel")),
    url(r'^', include("content.urls", namespace="content")),

    url(r'^auth/', include("base_user.urls", namespace="base-user")),
)
# ]

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^about/$', about, name='about'),
	# url(r'^error_404/$', error_404, name='error_404'),
	url(r'^programs/$', search, name='search'),
	url(r'^programs/deatil-(?P<id>\d+)/(?P<slug>[\w-]+)/$', program_detail, name='program-detail'),
	url(r'^contact/$', contact, name='contact-us'),
	url(r'^online-exam/$', online_exam, name='online-exam'),
	url(r'^online-exam/detail/(?P<id>[\w-]+)/$', online_exam_detail, name='online-exam-detail'),
	url(r'^online-exam/detail/(?P<id>[\w-]+)/check/$', online_exam_detail_check, name='online-exam-detail-check'),
	url(r'^page/(?P<slug>[\w-]+)/$', static_page, name='static-page'),

]

panel/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [

    url(r'^$', dashboard, name='dashboard'),
    url(r'^user/list/$', user_list, name='user-list'),
    url(r'^user/create/', user_create, name='user-create'),
    url(r'^user/edit/(?P<id>[0-9]+)/', user_edit, name='user-edit'),

    url(r'^appeal/list/$', appeal_list, name='appeal-list'),
    url(r'^appeal/view/(?P<id>[0-9]+)/', appeal_view, name='appeal-view'),

    url(r'^appeal-language-course/list/$', appeal_language_course_list, name='appeal-language-course-list'),
    url(r'^appeal-language-course/view/(?P<id>[0-9]+)/', appeal_language_course_view, name='appeal--language-course-view'),
]

content/models.py
import uuid

from django.conf import settings
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from hvad.models import TranslatableModel, TranslatedFields

from general.functions import path_and_rename, send_html_mail
from django.utils.translation import ugettext as _
from django.db.models import signals, Q


# Create your models here.
class MainSystemInfo(TranslatableModel):
    image = models.ImageField(upload_to=path_and_rename, null=True, blank=True)
    logo_white = models.ImageField(upload_to=path_and_rename, null=True, blank=True)
    logo_colored = models.ImageField(upload_to=path_and_rename, null=True, blank=True)

    phone = models.CharField(max_length=500, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)

    certificate_count = models.IntegerField(default=0)
    partner_count = models.IntegerField(default=0)
    student_count = models.IntegerField(default=0)

    site_url = models.URLField("Url",max_length=255, null=True, blank=True)

    site_name = models.CharField("Site name",max_length=255, null=True, blank=True)
    translations = TranslatedFields(
        site_index_title_part1 = models.CharField(max_length=255, null=True, blank=True),
        site_index_title_part2 = models.CharField(max_length=255, null=True, blank=True),
        site_slogan = models.CharField("Site slogan",max_length=255),
        about_text = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True),
        short_title = models.CharField("Uzun slogan",max_length=255,blank=True,null=True,default=''),
        short_desc = models.CharField("Qısa təsvir",max_length=255,blank=True,null=True,default=''),
        youtube_video_url = models.URLField("Youtube video url",blank=True,null=True,default=''),
        desc = RichTextUploadingField("Təsvir",config_name='awesome_ckeditor',blank=True,null=True,default=''),
        meta_description = models.CharField(max_length=255,blank=True,null=True),
        meta_keywords = models.TextField(blank=True,null=True),

    )


    about_menu = models.BooleanField(default=True)
    language_course_menu = models.BooleanField(default=True)
    programs_menu = models.BooleanField(default=True)
    blog_menu = models.BooleanField(default=True)
    contact_menu = models.BooleanField(default=True)

    success_story_menu = models.BooleanField(default=True)
    how_does_works_menu = models.BooleanField(default=True)
    why_us_menu = models.BooleanField(default=True)

    certificates_section_menu = models.BooleanField(default=True)
    app_section_menu = models.BooleanField(default=True)
    video_section_menu = models.BooleanField(default=True)
    teacher_section_menu = models.BooleanField(default=True)
    partner_section_menu = models.BooleanField(default=True)

    created_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.site_name
    class Meta:
        verbose_name  = 'Əsas tənzimləmələr'
        verbose_name_plural  = 'Əsas tənzimləmələr'

class WhyUs(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        short_text = models.CharField(max_length=500),
        content = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True),
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    class Meta:
        verbose_name  = 'Niyə biz bölməsi'
        verbose_name_plural  = 'Niyə biz bölmələri'


class HowWork(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        text = models.TextField(max_length=1000)
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    class Meta:
        verbose_name  = 'Sistem necə işləyir bölməsi'
        verbose_name_plural  = 'Sistem necə işləyir bölmələri'


class EducationLanguage(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        short_text = models.CharField(max_length=500),
        content = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True),
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    class Meta:
        verbose_name  = 'Təhsil dili'
        verbose_name_plural  = 'Təhsil dilləri'



class LanguageCourse(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    language = models.ForeignKey('EducationLanguage')
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        short_text = models.CharField(max_length=500),
        content = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    class Meta:
        verbose_name  = 'Dil kursu'
        verbose_name_plural  = 'Dil kursları'

class Foundation(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    country = models.ForeignKey('EducationCountry')
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        short_text = models.CharField(max_length=500),
        content = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True),
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    class Meta:
        verbose_name  = 'Department'
        verbose_name_plural  = 'Departmentlər'



class EducationCountry(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        short_text = models.CharField(max_length=500),
        content = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True),
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    class Meta:
        verbose_name  = 'Təshsil verən ölkə'
        verbose_name_plural  = 'Təshsil verən ölkələr'



class Profession(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        short_text = models.CharField(max_length=500),
        content = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    class Meta:
        verbose_name  = 'İxtisas'
        verbose_name_plural  = 'İxtisaslar'



class ProfessionSection(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        short_text = models.CharField(max_length=500),
        content = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    class Meta:
        verbose_name  = 'İxtisas bölməsi'
        verbose_name_plural  = 'İxtisas bölmələri'



class  SuccessStory(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        short_title = models.CharField(max_length=10),
        content = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    class Meta:
        verbose_name  = 'Uğur hekayəsi'
        verbose_name_plural  = 'Uğur hekayələri'



class StaticPage(TranslatableModel):
    parent = models.ForeignKey('self',blank=True,null=True)
    unique_title = models.CharField(max_length=255)
    translations = TranslatedFields(
        title = models.CharField(max_length=255),
        short_title = models.CharField(max_length=500),
        content = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True),
    )
    image = models.ImageField(max_length=500,upload_to=path_and_rename, blank=True,null=True)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.unique_title
    def get_parents(self):
        return StaticPage.objects.filter(parent=self)
    class Meta:
        verbose_name  = 'Statik səhifə'
        verbose_name_plural  = 'Statik səhifələr'


class  Partner(TranslatableModel):
    unique_title = models.CharField(max_length=255)
    translations = TranslatedFields(
        title = models.CharField(max_length=255),

panel/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from hvad.models import TranslatedFields, TranslatableModel

from general.functions import path_and_rename




class Appeal(models.Model):
    first_name = models.CharField(max_length=255,blank=True,null=True,default='')
    last_name = models.CharField(max_length=255,blank=True,null=True,default='')
    email = models.EmailField(blank=True,null=True,default='')
    note = models.TextField(max_length=255,blank=True,null=True,default='')
    phone = models.CharField(max_length=255)
    country = models.ForeignKey('content.EducationCountry',)
    language = models.ForeignKey('content.EducationLanguage',)
    profession = models.ForeignKey('content.Profession',)
    profession_section = models.ForeignKey('content.ProfessionSection',)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.phone
    def get_full_name(self):
        return "{} {}".format(self.first_name,self.last_name)
    class Meta:
        verbose_name  = 'Təhsil üçün müraciət'
        verbose_name_plural  = 'Təhsil üçün müraciətlər'



class AppealLanguageCourse(models.Model):
    course = models.ForeignKey('content.LanguageCourse',)
    first_name = models.CharField(max_length=255,default='')
    last_name = models.CharField(max_length=255,default='')
    email = models.EmailField(blank=True,default='')
    phone = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.phone
    def get_full_name(self):
        return "{} {}".format(self.first_name,self.last_name)
    class Meta:
        verbose_name  = 'Kursa olan müraciət'
        verbose_name_plural  = 'Kursa olan müraciətlər'




class AppealProgram(models.Model):
    program = models.ForeignKey('content.Program',)
    first_name = models.CharField(max_length=255,default='')
    last_name = models.CharField(max_length=255,default='')
    email = models.EmailField(blank=True,default='')
    phone = models.CharField(max_length=255)
    note = models.TextField(blank=True,null=True,default='')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.phone
    def get_full_name(self):
        return "{} {}".format(self.first_name,self.last_name)
    class Meta:
        verbose_name  = 'Proqrama olan müraciət'
        verbose_name_plural  = 'Proqrama olan müraciətlər'

templates/panel/appeals/appeal-form.html
{% extends 'base-profile.html' %}
{% load static %}
{% load i18n %}

{% block css_block %}

  <link rel="stylesheet" href="{% static 'local/profile/vendors/jsgrid/jsgrid.min.css' %}">
  <link rel="stylesheet" href="{% static 'local/profile/vendors/jsgrid/jsgrid-theme.min.css' %}">
  <style>
        #js-grid{
            height: 500px;
            width: 100%;

        }
  </style>
    <style>
.no-js #form-loader { display: none;  }
.js #form-loader { display: block; position: absolute; left: 100px; top: 0; }
.se-pre-con {
	position: fixed;
	left: 0px;
	top: 0px;
	width: 100%;
	height: 100%;
	z-index: 999999;
	background: url(http://smallenvelop.com/wp-content/uploads/2014/08/Preloader_2.gif) center no-repeat #ffffffab;
}

</style>
{% endblock %}
{% block content_block %}
        <div class="content-wrapper">
          <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">{% trans 'User' %}</h4>
                    {% if data_obj %}
                    <p class="card-description">
                        {{ data_obj.title }}
                    </p>
                    {% endif %}
                  <form class="forms-sample" method="post" action="" id="main-form-data">
                      {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                        {{ form.name }}
                        {% if form.name.errors %}
                            {% for item_error in form.name.errors %}
                                <label id="{{ form.name.id_for_label }}-error" class="error mt-2 text-danger" for="{{ form.name.id_for_label }}">{{ item_error }}</label>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.surname.id_for_label }}">{{ form.surname.label }}</label>
                        {{ form.surname }}
                        {% if form.surname.errors %}
                            {% for item_error in form.surname.errors %}
                                <label id="{{ form.surname.id_for_label }}-error" class="error mt-2 text-danger" for="{{ form.surname.id_for_label }}">{{ item_error }}</label>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                        {{ form.email }}
                        {% if form.email.errors %}
                            {% for item_error in form.email.errors %}
                                <label id="{{ form.email.id_for_label }}-error" class="error mt-2 text-danger" for="{{ form.email.id_for_label }}">{{ item_error }}</label>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                        {{ form.phone }}
                        {% if form.phone.errors %}
                            {% for item_error in form.phone.errors %}
                                <label id="{{ form.phone.id_for_label }}-error" class="error mt-2 text-danger" for="{{ form.phone.id_for_label }}">{{ item_error }}</label>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.usertype.id_for_label }}">{{ form.usertype.label }}</label>
                        {{ form.usertype }}
                        {% if form.usertype.errors %}
                            {% for item_error in form.usertype.errors %}
                                <label id="{{ form.usertype.id_for_label }}-error" class="error mt-2 text-danger" for="{{ form.usertype.id_for_label }}">{{ item_error }}</label>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                        {{ form.password }}
                        {% if form.password.errors %}
                            {% for item_error in form.password.errors %}
                                <label id="{{ form.password.id_for_label }}-error" class="error mt-2 text-danger" for="{{ form.password.id_for_label }}">{{ item_error }}</label>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.retype_password.id_for_label }}">{{ form.retype_password.label }}</label>
                        {{ form.retype_password }}
                        {% if form.retype_password.errors %}
                            {% for item_error in form.retype_password.errors %}
                                <label id="{{ form.retype_password.id_for_label }}-error" class="error mt-2 text-danger" for="{{ form.retype_password.id_for_label }}">{{ item_error }}</label>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">{% trans 'Submit' %}</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    <!-- content-wrapper ends -->
    {% endblock %}
  {% block js_block %}
<script type='text/javascript' src="https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/dist/jquery.inputmask.bundle.js"></script>
    <script>
        $("#{{ form.phone.id_for_label }}").inputmask({"mask": "(999) 999-9999"});
    </script>
<script>
    {% if messages %}
        {% for message in messages %}
          swal({
            title: '{% trans 'Congratulations' %}!',
            icon: 'success',
            text: '{{ message }}',
            button: {
              text: "{% trans 'OK' %}",
              value: true,
              visible: true,
              className: "btn btn-primary"
            }
          });
        {% endfor %}
    {% endif %}


    $(".se-pre-con").hide();
    var form_submit = false;
        $( "#main-form-data" ).submit(function( event ) {
          {#alert( "Handler for .submit() called." );#}
          event.preventDefault();
          if (!form_submit){
              form_submit = true;
                $(".se-pre-con").show();
                $.ajax({
                    url: '',
                    type: 'post',
                      data: new FormData(this), // Data sent to server, a set of key/value pairs (i.e. form fields and values)
                      contentType: false, // The content type used when sending data to the server.
                      cache: false, // To unable request pages to be cached
                      processData: false,
                    success: function(data){
                      $(".se-pre-con").hide();
                      if (data['message_code']){
                        Swal.fire({
                            type: 'success',
                            title: '{% trans 'Uğurlu' %}',
                            text: data['message_title']
                        });
                        setTimeout(function(){
                            window.location.href = data['redirect_url'];
                        }, 2000);
                      }else{
                        form_submit = false;
                        Swal.fire({
                            type: 'error',
                            title: data['message_title'],
                            html: data['message_text']
                        });
                      }
                    },
                }).error(function (err) {
                        $(".se-pre-con").hide();
                        form_submit = false;
                        Swal.fire({
                            type: 'error',
                            title: '{% trans 'Xəta baş verdi' %}',
                            html: err.toString(),
                        });
                  });
          }else{
            $(".se-pre-con").hide();
            Swal.fire({
                type: 'info',
                title: '{% trans 'Gözləyin' %}',
                {#html: err.toString(),#}
            });
          }
        });
    </script>
    <script>
        activeMenu('ui-appeals');
    </script>
  {% endblock %}

templates/panel/appeals/section-form.html
{% extends 'base-profile.html' %}
{% load static %}
{% load i18n %}

{% block css_block %}

  <link rel="stylesheet" href="{% static 'local/profile/vendors/jsgrid/jsgrid.min.css' %}">
  <link rel="stylesheet" href="{% static 'local/profile/vendors/jsgrid/jsgrid-theme.min.css' %}">
  <style>
        #js-grid{
            height: 500px;
            width: 100%;

        }
  </style>
{% endblock %}
{% block content_block %}
        <div class="content-wrapper">
          <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">{% trans 'Section' %}</h4>
                    {% if data_obj %}
                    <p class="card-description">
                        {{ data_obj.title }}
                    </p>
                    {% endif %}
                  <form class="forms-sample" method="post" action="">
                      {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">{% trans 'Title' %}</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="id_short_text">{% trans 'Short text' %}</label>
                        {{ form.short_text }}
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">{% trans 'Submit' %}</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    <!-- content-wrapper ends -->
    {% endblock %}
  {% block js_block %}

<script src="{% static 'local/profile/vendors/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'local/profile/vendors/jquery.avgrund/jquery.avgrund.min.js' %}"></script>
<script>
    {% if messages %}
        {% for message in messages %}
          swal({
            title: '{% trans 'Congratulations' %}!',
            icon: 'success',
            text: '{{ message }}',
            button: {
              text: "{% trans 'OK' %}",
              value: true,
              visible: true,
              className: "btn btn-primary"
            }
          });
        {% endfor %}
    {% endif %}
</script>
    <script>
        activeMenu('ui-appeals');
    </script>
  {% endblock %}