educaction_proj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve

# from content.views import dashboard
from home.views import *
from django.views import static
from django.conf import settings
from general import set_lang as core_views
# from home import views as home_views
# from django.conf.urls import handler404, handler500

# from general import set_lang as core_views


urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media'),
]
# handler404 = home_views.error_404
# translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
# urlpatterns += [

    url(r'^set-language/$', core_views.set_language, name='set_language'),
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^', include("home.urls", namespace="home")),
    url(r'^panel/', include("panel.urls", namespace="panel")),
    url(r'^', include("content.urls", namespace="content")),

    url(r'^auth/', include("base_user.urls", namespace="base-user")),
)
# ]

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^about/$', about, name='about'),
	# url(r'^error_404/$', error_404, name='error_404'),
	url(r'^programs/$', search, name='search'),
	url(r'^programs/deatil-(?P<id>\d+)/(?P<slug>[\w-]+)/$', program_detail, name='program-detail'),
	url(r'^contact/$', contact, name='contact-us'),
	url(r'^online-exam/$', online_exam, name='online-exam'),
	url(r'^online-exam/detail/(?P<id>[\w-]+)/$', online_exam_detail, name='online-exam-detail'),
	url(r'^online-exam/detail/(?P<id>[\w-]+)/check/$', online_exam_detail_check, name='online-exam-detail-check'),
	url(r'^page/(?P<slug>[\w-]+)/$', static_page, name='static-page'),

]

panel/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [

    url(r'^$', dashboard, name='dashboard'),
    url(r'^user/list/$', user_list, name='user-list'),
    url(r'^user/create/', user_create, name='user-create'),
    url(r'^user/edit/(?P<id>[0-9]+)/', user_edit, name='user-edit'),

    url(r'^appeal/list/$', appeal_list, name='appeal-list'),
    url(r'^appeal/view/(?P<id>[0-9]+)/', appeal_view, name='appeal-view'),

    url(r'^appeal-language-course/list/$', appeal_language_course_list, name='appeal-language-course-list'),
    url(r'^appeal-language-course/view/(?P<id>[0-9]+)/', appeal_language_course_view, name='appeal--language-course-view'),
]

templates/panel/appeals/include/list-item.html
<tr>
    <td>{{ for_i }}</td>
    <td>{{ data_item.first_name }}</td>
    <td>{{ data_item.last_name }}</td>
    <td>{{ data_item.phone }}</td>
    <td>{{ data_item.program.country.title }}</td>
    <td>{{ data_item.program.language.title }}</td>
    <td>{{ data_item.program.profession.title }}</td>
    <td>{{ data_item.program.profession_section.title }}</td>
    <td>{{ data_item.date|date:'d.m.Y H:i' }}</td>
    <td>
        <a style="padding: 10px;" href="{% url 'panel:appeal-view' data_item.id %}" class="btn btn-icon btn-square btn-warning">
            <i class="ti-pencil-alt"></i>
        </a>
    </td>
</tr>

templates/panel/appeals/include/main.html
{% load static %}{% load i18n %}

<div class="jsgrid-grid-body" style="height: 442px;">
    <table class="jsgrid-table">
        <thead class="jsgrid-grid-header jsgrid-header-scrollbar">
            <tr class="jsgrid-header-row">
                <th class="jsgrid-header-cell" >n</th>
                <th class="jsgrid-header-cell" >{% trans 'Name' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Surname' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Phone' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Country' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Language' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Profession' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Profession section' %}</th>
                <th class="jsgrid-header-cell" >{% trans 'Date' %}</th>
                <th class="jsgrid-header-cell" >/</th>
            </tr>
        </thead>
        <tbody id="">
            {% autoescape off %}
            {{ list_html }}
            {% endautoescape %}
        </tbody>
    </table>
</div>